blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/denex-io/denex-network-manager/issues
    about: Ask questions and discuss usage by opening an issue.
