// SPDX-License-Identifier: Apache-2.0
// Copyright Cumberland Applications LLC 2026
//
// Builds the npm package using dnt (Deno to Node Transform).
// Usage: deno run --allow-all scripts/build_npm.ts <version>
// Example: deno run --allow-all scripts/build_npm.ts 0.1.0-beta.1

import { build, emptyDir } from 'jsr:@deno/dnt@^0.42.3';
import { join } from 'node:path';

const version = Deno.args[0];
if (!version) {
  console.error('Usage: deno run --allow-all scripts/build_npm.ts <version>');
  Deno.exit(1);
}

await emptyDir('./npm');

await build({
  entryPoints: [
    { name: '.', path: './src/mod.ts' },
    { name: './sdk', path: './src/sdk/mod.ts' },
    { name: './types', path: './src/types/mod.ts' },
  ],
  outDir: './npm',
  shims: { deno: false },
  test: false,
  compilerOptions: {
    target: 'ES2020',
    lib: ['ES2020'],
  },
  package: {
    name: '@denex/network-manager',
    version,
    description: 'SDK and CLI for running Canton Network LocalNets from a single YAML file',
    license: 'Apache-2.0',
    engines: { node: '>=18' },
    bin: { dnm: './bin/dnm.js' },
    keywords: [
      'canton',
      'daml',
      'digital-asset',
      'testcontainers',
      'docker',
      'distributed-ledger',
      'localnet',
      'splice',
    ],
    repository: {
      type: 'git',
      url: 'git+https://github.com/denex-io/denex-localnet.git',
    },
    bugs: { url: 'https://github.com/denex-io/denex-localnet/issues' },
    homepage: 'https://github.com/denex-io/denex-localnet#readme',
  },
  postBuild() {
    Deno.copyFileSync('LICENSE', 'npm/LICENSE');
    Deno.copyFileSync('README.md', 'npm/README.md');

    // Create bin directory and platform-selector wrapper for the dnm CLI binary.
    // The actual compiled binaries (dnm-linux-x64, dnm-darwin-arm64, etc.) are
    // copied into npm/bin/ by the CI publish job after deno compile runs.
    Deno.mkdirSync('npm/bin', { recursive: true });
    Deno.writeTextFileSync(join('npm', 'bin', 'dnm.js'), dnmWrapperScript());
  },
});

console.log(`\nBuilt @denex/network-manager@${version} → ./npm/`);

function dnmWrapperScript(): string {
  return `#!/usr/bin/env node
// Auto-generated by scripts/build_npm.ts — do not edit manually.
// Selects the pre-compiled dnm binary for the current platform and executes it.
'use strict';
const { execFileSync } = require('child_process');
const { existsSync } = require('fs');
const path = require('path');
const { platform, arch } = process;

const PLATFORM_BINS = {
  'linux-x64': 'dnm-linux-x64',
  'linux-arm64': 'dnm-linux-arm64',
  'darwin-x64': 'dnm-darwin-x64',
  'darwin-arm64': 'dnm-darwin-arm64',
  'win32-x64': 'dnm-win-x64.exe',
};

const key = platform + '-' + arch;
const binName = PLATFORM_BINS[key];

if (!binName) {
  console.error(
    \`dnm: unsupported platform '\${key}'. Supported: \${Object.keys(PLATFORM_BINS).join(', ')}.\\n\` +
    \`Please open an issue at https://github.com/denex-io/denex-localnet/issues\`
  );
  process.exit(1);
}

const binPath = path.join(__dirname, binName);

if (!existsSync(binPath)) {
  console.error(
    \`dnm: binary not found at \${binPath}.\\n\` +
    \`This is a packaging bug — please file an issue at https://github.com/denex-io/denex-localnet/issues\`
  );
  process.exit(1);
}

try {
  execFileSync(binPath, process.argv.slice(2), { stdio: 'inherit' });
} catch (/** @type {any} */ e) {
  process.exit(e.status ?? 1);
}
`;
}
