/**
 * Environment file generator for Canton LocalNet.
 *
 * Generates environment variables needed by Docker containers
 * for database configuration, port mappings, auth settings, etc.
 */

import type { LocalNetConfig, ValidatorConfig } from '../types/config.ts';
import { DEFAULT_AUDIENCE, normalizeValidators } from '../types/config.ts';
import {
  DEFAULT_BASE_PORT,
  getSvPorts,
  getValidatorPorts,
  PORT_SUFFIXES,
  SV_INTERNAL_PORTS,
} from '../utils/ports.ts';

export interface EnvGeneratorConfig {
  dbUser?: string;
  dbPassword?: string;
  dbServer?: string;
  dbPort?: number;
}

const ENV_DEFAULTS: Required<EnvGeneratorConfig> = {
  dbUser: 'cnadmin',
  dbPassword: 'supersafe',
  dbServer: 'postgres',
  dbPort: 5432,
};

/**
 * Generate the common environment variables shared across all containers.
 */
export function generateCommonEnv(
  config: LocalNetConfig,
  envConfig: EnvGeneratorConfig = {},
): string {
  const opts = { ...ENV_DEFAULTS, ...envConfig };
  const normalizedValidators = normalizeValidators(config.validators);
  const basePort = config.basePort ?? DEFAULT_BASE_PORT;

  // Build profile flags
  const svProfile = 'on';
  const validatorProfiles = normalizedValidators.map(() => 'on');

  const svPorts = getSvPorts(basePort);

  return `# Common environment - generated by denex-network-manager
# Do not edit manually

# Profiles
SV_PROFILE=${svProfile}
${
    normalizedValidators.map((_, i) => `VALIDATOR_${i + 1}_PROFILE=${validatorProfiles[i]}`).join(
      '\n',
    )
  }

# Database configuration
DB_USER=${opts.dbUser}
DB_PASSWORD=${opts.dbPassword}
DB_SERVER=${opts.dbServer}
DB_PORT=${opts.dbPort}

# Port suffixes (used by containers)
PARTICIPANT_LEDGER_API_PORT_SUFFIX=${PORT_SUFFIXES.ledgerApi}
PARTICIPANT_ADMIN_API_PORT_SUFFIX=${PORT_SUFFIXES.adminApi}
PARTICIPANT_JSON_API_PORT_SUFFIX=${PORT_SUFFIXES.jsonApi}
VALIDATOR_ADMIN_API_PORT_SUFFIX=${PORT_SUFFIXES.validatorAdminApi}
CANTON_HTTP_HEALTHCHECK_PORT_SUFFIX=${PORT_SUFFIXES.httpHealth}
CANTON_GRPC_HEALTHCHECK_PORT_SUFFIX=${PORT_SUFFIXES.grpcHealth}

# UI Ports
SV_UI_PORT=${svPorts.webUi}
${
    normalizedValidators.map((_, i) =>
      `VALIDATOR_${i + 1}_UI_PORT=${getValidatorPorts(i, basePort).webUi}`
    ).join('\n')
  }

# Splice configuration
SPLICE_SV_IS_DEVNET=true
SPLICE_APP_VALIDATOR_AUTH_AUDIENCE=${DEFAULT_AUDIENCE}
SPLICE_APP_CONTACT_POINT=

# Wallet/UI configuration
SPLICE_APP_UI_NETWORK_NAME=LocalNet
SPLICE_APP_UI_NETWORK_FAVICON_URL=https://www.hyperledger.org/hubfs/hyperledgerfavicon.png
SPLICE_APP_UI_AMULET_NAME=Amulet
SPLICE_APP_UI_AMULET_NAME_ACRONYM=AMT
SPLICE_APP_UI_NAME_SERVICE_NAME=Amulet Name Service
SPLICE_APP_UI_NAME_SERVICE_NAME_ACRONYM=ANS
SPLICE_APP_UI_AUTH_AUDIENCE=${DEFAULT_AUDIENCE}
SPLICE_APP_UI_UNSAFE=false
SPLICE_APP_UI_HTTP_URL=true

# Migration
MIGRATION_ID=0
LATEST_PACKAGES_ONLY=true
`;
}

/**
 * Generate PostgreSQL-specific environment variables.
 */
export function generatePostgresEnv(
  config: LocalNetConfig,
  envConfig: EnvGeneratorConfig = {},
): string {
  const opts = { ...ENV_DEFAULTS, ...envConfig };
  const normalizedValidators = normalizeValidators(config.validators);

  // Build list of databases to create
  const databases: string[] = [];

  // SV databases
  databases.push('participant-sv');
  databases.push('validator-sv');
  databases.push('sequencer');
  databases.push('mediator');
  databases.push('scan');
  databases.push('sv');

  // Validator databases
  for (const validator of normalizedValidators) {
    databases.push(`participant-${validator.name}`);
    databases.push(`validator-${validator.name}`);
  }

  const dbLines = databases.map(
    (db, i) => `CREATE_DATABASE_${String(i + 1).padStart(2, '0')}=${db}`,
  );

  return `# PostgreSQL environment - generated by denex-network-manager
POSTGRES_USER=\${DB_USER}
POSTGRES_PASSWORD=\${DB_PASSWORD}
POSTGRES_DB=${opts.dbServer}
${dbLines.join('\n')}
`;
}

/**
 * Generate Splice-specific environment variables.
 */
export function generateSpliceEnv(
  config: LocalNetConfig,
): string {
  const normalizedValidators = normalizeValidators(config.validators);

  // Generate onboarding secrets for each validator
  const onboardingSecrets = normalizedValidators.map(
    (v) =>
      `${
        v.name.toUpperCase().replace(/-/g, '_')
      }_VALIDATOR_ONBOARDING_SECRET=${v.name}-onboarding-secret`,
  );

  return `# Splice environment - generated by denex-network-manager

# Traffic topups
TARGET_TRAFFIC_THROUGHPUT=20000
MIN_TRAFFIC_TOPUP_INTERVAL=1m

# SV addresses
SPLICE_APP_VALIDATOR_SV_SPONSOR_ADDRESS=http://localhost:${SV_INTERNAL_PORTS.svAdmin}
SPLICE_APP_VALIDATOR_SCAN_ADDRESS=http://localhost:${SV_INTERNAL_PORTS.scanAdmin}

# Onboarding secrets
${onboardingSecrets.join('\n')}

# Migration settings
MIGRATION_ID=\${MIGRATION_ID:-0}
LATEST_PACKAGES_ONLY=\${LATEST_PACKAGES_ONLY:-true}
`;
}

/**
 * Generate SV-specific auth environment variables.
 */
export function generateSvAuthEnv(
  _config: LocalNetConfig,
): string {
  return `# SV Auth environment - generated by denex-network-manager
AUTH_SV_AUDIENCE=${DEFAULT_AUDIENCE}
AUTH_SV_VALIDATOR_USER_NAME=ledger-api-user
AUTH_SV_WALLET_ADMIN_USER_NAME=sv
SPLICE_APP_UI_AUTH_AUDIENCE=\${AUTH_SV_AUDIENCE}
SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_AUDIENCE=\${AUTH_SV_AUDIENCE}
`;
}

/**
 * Generate validator-specific auth environment variables.
 */
export function generateValidatorAuthEnv(
  validator: ValidatorConfig,
  _config: LocalNetConfig,
): string {
  const partyHint = validator.parties?.[0]?.hint ?? validator.name;
  const envPrefix = validator.name.toUpperCase().replace(/-/g, '_');

  return `# ${validator.name} Auth environment - generated by denex-network-manager
${envPrefix}_PARTY_HINT=${partyHint}
AUTH_${envPrefix}_AUDIENCE=${DEFAULT_AUDIENCE}
AUTH_${envPrefix}_VALIDATOR_USER_NAME=ledger-api-user
AUTH_${envPrefix}_WALLET_ADMIN_USER_NAME=${validator.name}
SPLICE_APP_UI_AUTH_AUDIENCE=\${AUTH_${envPrefix}_AUDIENCE}
SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_AUDIENCE=\${AUTH_${envPrefix}_AUDIENCE}
`;
}

/**
 * Generate a merged environment file containing all variables.
 * This is a single file that can be used with Docker Compose --env-file.
 */
export function generateMergedEnv(
  config: LocalNetConfig,
  envConfig: EnvGeneratorConfig = {},
): string {
  const normalizedValidators = normalizeValidators(config.validators);

  let env = generateCommonEnv(config, envConfig);
  env += '\n';
  env += generatePostgresEnv(config, envConfig);
  env += '\n';
  env += generateSpliceEnv(config);
  env += '\n';
  env += generateSvAuthEnv(config);

  for (const validator of normalizedValidators) {
    env += '\n';
    env += generateValidatorAuthEnv(validator, config);
  }

  return env;
}

/**
 * Generate port mapping environment variables for all components.
 */
export function generatePortMappingEnv(
  config: LocalNetConfig,
): string {
  const normalizedValidators = normalizeValidators(config.validators);
  const basePort = config.basePort ?? DEFAULT_BASE_PORT;
  const svPorts = getSvPorts(basePort);

  const lines: string[] = [
    '# Port mappings - generated by denex-network-manager',
    '',
    '# Super Validator ports',
    `SV_LEDGER_API_PORT=${svPorts.ledgerApi}`,
    `SV_ADMIN_API_PORT=${svPorts.adminApi}`,
    `SV_VALIDATOR_ADMIN_API_PORT=${svPorts.validatorAdminApi}`,
    `SV_JSON_API_PORT=${svPorts.jsonApi}`,
    `SV_HTTP_HEALTH_PORT=${svPorts.httpHealth}`,
    `SV_GRPC_HEALTH_PORT=${svPorts.grpcHealth}`,
    '',
    '# SV Internal ports',
    `SV_SEQUENCER_PUBLIC_PORT=${SV_INTERNAL_PORTS.sequencerPublic}`,
    `SV_SEQUENCER_ADMIN_PORT=${SV_INTERNAL_PORTS.sequencerAdmin}`,
    `SV_MEDIATOR_ADMIN_PORT=${SV_INTERNAL_PORTS.mediatorAdmin}`,
    `SV_SCAN_ADMIN_PORT=${SV_INTERNAL_PORTS.scanAdmin}`,
    `SV_SV_ADMIN_PORT=${SV_INTERNAL_PORTS.svAdmin}`,
  ];

  for (let i = 0; i < normalizedValidators.length; i++) {
    const validator = normalizedValidators[i];
    const ports = getValidatorPorts(i, basePort);
    const envPrefix = validator.name.toUpperCase().replace(/-/g, '_');

    lines.push('');
    lines.push(`# ${validator.name} ports`);
    lines.push(`${envPrefix}_LEDGER_API_PORT=${ports.ledgerApi}`);
    lines.push(`${envPrefix}_ADMIN_API_PORT=${ports.adminApi}`);
    lines.push(`${envPrefix}_VALIDATOR_ADMIN_API_PORT=${ports.validatorAdminApi}`);
    lines.push(`${envPrefix}_JSON_API_PORT=${ports.jsonApi}`);
    lines.push(`${envPrefix}_HTTP_HEALTH_PORT=${ports.httpHealth}`);
    lines.push(`${envPrefix}_GRPC_HEALTH_PORT=${ports.grpcHealth}`);
  }

  return lines.join('\n') + '\n';
}
